language: java

jdk:
  - openjdk11

os:
  - linux

stages:
  - compile
  - test

jobs:
  include:
    - stage: test
      script:  ./gradlew clean jar

    - stage: deploy
      script:  ./gradlew server:test