language: java

dist: bionic

jdk:
  - openjdk11

os:
  - linux

stages:
  # - compile
  # - test
  # - deploy
  - publishWindows
  - publishmac

before_install:
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then export DISPLAY=:99.0 && /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16; fi


# before_cache:
#   - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
#   - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
# cache:
#   directories:
#     - $HOME/.gradle/caches/
#     - $HOME/.gradle/wrapper/

jobs:
  include:
    - os: osx
      stage: publishmac
      jdk:
        - openjdk14
      language: java
      script:
        - ./gradlew publishDMG --info

    - os: windows
      stage: publishWindows
      language: bash

      before_install:
        - powershell Install-WindowsFeature Net-Framework-Core
        - cinst -y wixtoolset

      install:
        - choco install powershell
        - choco install adoptopenjdk --version 14.0.1.7
        - export JAVA_HOME='C:\Program Files\adoptopenjdk\jdk-14.0.1.7-hotspot'

        - choco install wixtoolset --version 3.11.2
       # - choco install nuget.commandline
       # - nuget install WiX.Toolset
       # - export PATH=$PATH;.\WiX.Toolset.3.9.1208.0\tools\wix\
       # - echo $PATH
        - ls 'C:\Program Files\adoptopenjdk'
        - dir 'C:\Program Files\adoptopenjdk'
      #  - choco install innosetup # it's allready installed!

      script:
        - ./gradlew.bat client:jpackage publishMSI --info --stacktrace