language: java

dist: xenial

jdk:
  - openjdk11

os:
  - linux

stages:
  - compile
  - test

before_install:
  - if [[ "${TRAVIS_OS_NAME}" == linux ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi


cache:
  directories:
    - $HOME/.gradle

jobs:
  include:
    - stage: compile
      script:  ./gradlew clean jar

    - stage: test
      script:  ./gradlew server:test